## Code for Lecture 2

In [1]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [2]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


In [3]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello
5
hello world
hello world 12


In [4]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [5]:
age = 3
if age >= 18:
    print('adult')
elif age >= 6:
    print('teenager')
else:
    print('kid')

kid


In [6]:
classmates = ['Michael', 'Bob', 'Tracy']
print('classmates =', classmates) # classmates = ['Michael', 'Bob', 'Tracy']
print('len(classmates) =', len(classmates))  # len(classmates) = 3
print('classmates[0] =', classmates[0])# classmates[0] = Michael
print('classmates[1] =', classmates[1])
print('classmates[2] =', classmates[2])
print('classmates[-1] =', classmates[-1]) # classmates[-1] = Tracy
classmates.pop()
print('classmates =', classmates) # classmates = ['Michael', 'Bob']

classmates = ['Michael', 'Bob', 'Tracy']
len(classmates) = 3
classmates[0] = Michael
classmates[1] = Bob
classmates[2] = Tracy
classmates[-1] = Tracy
classmates = ['Michael', 'Bob']


In [7]:
classmates = ('Michael', 'Bob', 'Tracy')
print('classmates =', classmates)
print('len(classmates) =', len(classmates))
print('classmates[0] =', classmates[0])

# cannot modify tuple:
classmates[0] = 'Adam'

classmates = ('Michael', 'Bob', 'Tracy')
len(classmates) = 3
classmates[0] = Michael


TypeError: 'tuple' object does not support item assignment

In [9]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [10]:
names = ['Michael', 'Bob', 'Tracy']
for name in names:
    print(name)


for x in range(10):
    print(x)
# prints 0 - 9, each on its own line

animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

Michael
Bob
Tracy
0
1
2
3
4
5
6
7
8
9
#1: cat
#2: dog
#3: monkey


In [11]:
# compute 1+2+...+100
sum = 0
n = 1
while n <= 100:
    sum = sum + n
    n = n + 1
print(sum) # 5050



5050


In [12]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

[0, 1, 4, 9, 16]
[0, 4, 16]


In [13]:
d = {
    'Michael': 95,
    'Bob': 75,
    'Tracy': 85
}
print('d[\'Michael\'] =', d['Michael']) # d['Michael'] = 95
print('d[\'Bob\'] =', d['Bob']) # d['Bob'] = 75
print('d[\'Tracy\'] =', d['Tracy']) # d['Tracy'] = 85
print('d.get(\'Thomas\', -1) =', d.get('Thomas', -1)) # d.get('Thomas', -1) = -1

d['Michael'] = 95
d['Bob'] = 75
d['Tracy'] = 85
d.get('Thomas', -1) = -1


In [14]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

cute
True
wet
N/A
wet
N/A


In [15]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [16]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


In [17]:
s1 = set([1, 1, 2, 2, 3, 3])
print(s1)                   # {1, 2, 3}
s2 = set([2, 3, 4])
print(s1 & s2)              # {2, 3}
print(s1 | s2)              # {1, 2, 3, 4}

{1, 2, 3}
{2, 3}
{1, 2, 3, 4}


In [18]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

True
False
True
3
3
2


In [19]:
def fib(n=1): 
        a , b = 0, 1
        for i in range(n):
            a, b = b, a + b
            print(a)
        return a

print(fib(10))  # print 55 
print(fib())     # print 1

1
1
2
3
5
8
13
21
34
55
55
1
1


In [20]:
import random as rd
print(rd.random())                             # Random float:  0.0 <= x < 1.0
print(rd.uniform(2.5, 10.0) )                  # Random float:  2.5 <= x < 10.0
print(rd.gauss(0, 1))                          # Random float: Normal(0,1)
print(rd.randrange(10) )                       # Integer from 0 to 9 inclusive
print(rd.sample([10, 20, 30, 40, 50], k=4) )   # Four samples without replacement
print(rd.choices([10, 20, 30, 40, 50], k=4) )  # Four samples with replacement

0.8913779486805862
6.553027195991998
0.013591565964913269
9
[10, 30, 20, 50]
[10, 50, 30, 40]


In [21]:
def changeme( mylist ):
    # "This changes a passed list into this function"
    print ("Values inside the function before change: ", mylist)
    mylist[2]=50
    print ("Values inside the function after change: ", mylist)
    return

# Now you can call changeme function
mylist = [10,20,30]
changeme( mylist )
print ("Values outside the function: ", mylist)

Values inside the function before change:  [10, 20, 30]
Values inside the function after change:  [10, 20, 50]
Values outside the function:  [10, 20, 50]


In [22]:
import math
a = math.sin(2 * math.pi)
print(a)

-2.4492935982947064e-16


In [23]:
import os

f = open(os.getcwd()+'/data.txt', 'r') 
for line in f.readlines():
    print(line) 
f.close()

This is the first line.

This is the second line.

This is the third line.Python is great

Python is great



In [24]:
f = open(os.getcwd()+'/data.txt', 'r') 
while True:
    s=f.read(10)
    print(s)
    print('******************')
    if not s:
        break
f.close()

This is th
******************
e first li
******************
ne.
This i
******************
s the seco
******************
nd line.
T
******************
his is the
******************
 third lin
******************
e.Python i
******************
s great
Py
******************
thon is gr
******************
eat

******************

******************


In [25]:
with open(os.getcwd()+'/data.txt', 'r') as f: 
    # you may change the path to read the file
    for line in f.readlines():
        print(line) 


This is the first line.

This is the second line.

This is the third line.Python is great

Python is great



In [26]:
with open(os.getcwd()+'/data.txt', 'a+') as f: 
    f.write('Python is great\n')

In [27]:
with open(os.getcwd()+'/data.txt', 'r') as f: 
    for line in f.readlines():
        print(line.strip()) # delete "\n" at the rail
        

This is the first line.
This is the second line.
This is the third line.Python is great
Python is great
Python is great


In [28]:
with open(os.getcwd()+'/data.csv', 'r') as f: 
    for line in f.readlines():
        print(line.strip()) # delete "\n" at the rail
        

start node,end node,link length
1,2,2
1,3,4.5
2,3,6
2,4,3
3,4,5
1,2,2
1,3,4.5
2,3,6
2,4,3
3,4,5


In [29]:
with open(os.getcwd()+'/data.csv', 'r') as f: 
    print(f.read())

start node,end node,link length
1,2,2
1,3,4.5
2,3,6
2,4,3
3,4,5
1,2,2
1,3,4.5
2,3,6
2,4,3
3,4,5


In [30]:
import csv

with open(os.getcwd()+'/data.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            print(','.join(row))
            line_count += 1
        else:
            print(row)
            line_count += 1
    print(line_count)


start node,end node,link length
['1', '2', '2']
['1', '3', '4.5']
['2', '3', '6']
['2', '4', '3']
['3', '4', '5']
['1', '2', '2']
['1', '3', '4.5']
['2', '3', '6']
['2', '4', '3']
['3', '4', '5']
11


In [31]:
with open('employee_file.csv', mode='w') as employee_file:
    employee_writer = csv.writer(employee_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

    employee_writer.writerow(['John Smith', 'Accounting', 'November'])
    employee_writer.writerow(['Erica Meyers', 'IT', 'March'])

In [33]:
with open(os.getcwd()+'/data.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    data={}
    i=0
    j=0
    for row in csv_reader:
        if line_count == 0:
            print(','.join(row))
            line_count += 1
        else:
            for j in range(len(row)):
                data[i,j]=float(row[j])
            i=i+1
            print(row)
            line_count += 1
    print(line_count)
    print(data)

start node,end node,link length
['1', '2', '2']
['1', '3', '4.5']
['2', '3', '6']
['2', '4', '3']
['3', '4', '5']
['1', '2', '2']
['1', '3', '4.5']
['2', '3', '6']
['2', '4', '3']
['3', '4', '5']
11
{(0, 0): 1.0, (0, 1): 2.0, (0, 2): 2.0, (1, 0): 1.0, (1, 1): 3.0, (1, 2): 4.5, (2, 0): 2.0, (2, 1): 3.0, (2, 2): 6.0, (3, 0): 2.0, (3, 1): 4.0, (3, 2): 3.0, (4, 0): 3.0, (4, 1): 4.0, (4, 2): 5.0, (5, 0): 1.0, (5, 1): 2.0, (5, 2): 2.0, (6, 0): 1.0, (6, 1): 3.0, (6, 2): 4.5, (7, 0): 2.0, (7, 1): 3.0, (7, 2): 6.0, (8, 0): 2.0, (8, 1): 4.0, (8, 2): 3.0, (9, 0): 3.0, (9, 1): 4.0, (9, 2): 5.0}


In [34]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [35]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[0.2119564  0.65970294]
                             #             [0.82106931 0.45964519]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.98401829 0.14059861]
 [0.18967367 0.93891454]]


In [36]:
a = [[1,2],[3,4]]
print(a[1])
print(a[1][:])

[3, 4]
[3, 4]


In [37]:
A = np.array([[1,2,3],[4,5,6]])
print(A.size)                 # 6
print(A.shape)                # (2,3)
print(A)                      # [[1 2 3]
                              # [4 5 6]]
print(A[1,0])                 # 4
print(A[1])                   # [4 5 6]
print(A[-1])                  # [4 5 6]
print(A[:,0])                 # [1 4]
print(A.T)                    # [[1 4]
                              #  [2 5]
                              #  [3 6]]

6
(2, 3)
[[1 2 3]
 [4 5 6]]
4
[4 5 6]
[4 5 6]
[1 4]
[[1 4]
 [2 5]
 [3 6]]


In [38]:
a = np.array([1,2,3])
c = np.array([7,8,9])
print(a.dot(c))       # 50
print(a * c)          # [ 7 16 27]
print(a.T.dot(c))     # 50
print(np.dot(a, c))   # 50
print(np.outer(a,c))  # [[ 7  8  9]
                      #  [14 16 18]
                      #  [21 24 27]]

print(np.outer(c,a))  # [[ 7 14 21]
                      #  [ 8 16 24]
                      #  [ 9 18 27]]

print(A.dot(a))       # [13 13  6]
print(a.dot(A.T))     # [13 13  6]

50
[ 7 16 27]
50
50
[[ 7  8  9]
 [14 16 18]
 [21 24 27]]
[[ 7 14 21]
 [ 8 16 24]
 [ 9 18 27]]
[14 32]
[14 32]


In [39]:
A = np.array([[1,3,2],[3,2,2],[1,1,1]])
B = np.linalg.inv(A)
print(B)
print(A.dot(B) )

[[ 0.  1. -2.]
 [ 1.  1. -4.]
 [-1. -2.  7.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
b = np.array([2,4,1])
x = np.linalg.solve(A,b)
print(x)
print(A.dot(x))

[ 2.  2. -3.]
[2. 4. 1.]


$AV = VD$ 

In [41]:
print(np.linalg.det(A))
d, V = np.linalg.eig(A) 
D = np.diag(d)
# d is the eigenvalues of A，each column of V is a eigenvector of A
print(D)
print(V)
print(np.array_equal( V.dot(D), A.dot(V) ) ) 
# In theroy, AV=VD
print(np.allclose( V.dot(D), A.dot(V) ) ) 

-1.0
[[ 5.43745406  0.          0.        ]
 [ 0.         -1.55567275  0.        ]
 [ 0.          0.          0.11821869]]
[[-0.62369401 -0.77955319 -0.2551398 ]
 [-0.7205792   0.6233466  -0.48330607]
 [-0.30293794  0.06112151  0.83744786]]
False
True
